from selenium import webdriver
import time
driver=webdriver.Chrome(executable_path="C:\Drivers\Chrome\chromedriver.exe")
driver.get("https://www.jotform.com/")
print(driver.title)
driver.find_element_by_xpath("//a[.='IT’S FREE!']").click()
inputfields=driver.find_elements_by_class_name("formLabel")
print(len(inputfields))
time.sleep(5)
status=driver.find_element_by_id("fullname").is_enabled()
print(status)
driver.find_element_by_id("fullname").send_keys("poornima")
status=driver.find_element_by_id("fullname").is_displayed()
print(status)
status=driver.find_element_by_id("suEmail").is_enabled()
print(status)
driver.find_element_by_id("suEmail").send_keys("poorvi.gmail.com")
status=driver.find_element_by_id("suEmail").is_displayed()
print(status)
driver.close()